apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-nfs-bl
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: sbybz221092.sby.dst.ibm.com
    path: "/nfsshare"